### ISSUE TITLE
What to do about Discord bots?

### ISSUE THREAD

**Issue by shenanigansd** [letsbuilda/meta#1]
# Summary
What should we do with our Discord bots?

# Current bots
## Alais
A bot with a database.
This was intended to be our "main" bot.
It has role permissions by server in a database.
It currently has a half complete Sentry.io implementation stolen from Python Discord.

## Larkbot
A bot with an UwU command.
That's it.
It was intended to be a "fun" bot that was easy to contribute to, so my original idea was to avoid connecting to external services, to keep the scope small.
It does have an `!internal eval`, but the permissions IDs are currently hard-coded.
It is not currently setup on Sentry.io.

# Possible paths forward
## Consolidate around Alais
Move the UwU command to Alais, and then just delete Larkbot altogether

## Keep both bots
If we keep both bots, I think we should at least connect both to the database and Sentry.
As we're self hosting both of these for our own server(s), letting them share a DB should be fine, but we could always make a DB for each one.

## Other paths?
Are there other possible paths I haven't considered?

**Comment by Robin5605** [comment]
I think we keep both bots, it can't harm. Alais is to Larkbot as Python bot is to Sir Lancebot

**Comment by shenanigansd** [comment]
I think I agree.
What would the next step be? Creating a DB for Larkbot?
(I'm using DBs instead of stealing the YAML configs from PyDis to give people the option to create a multi-guild DB if they so desire)

**Comment by Robin5605** [comment]
What do you mean by "DB", in this context?
A completely seperate docker instance or database instance, or just a new database within the same instance?

**Comment by shenanigansd** [comment]
I was just speaking generically.
I would probably do the latter -- create a new logical database in the singular container.
I actually considered using the same database for both bots, because they'll overlap so much.

**Comment by shenanigansd** [comment]
We can keep both bots.
With https://github.com/letsbuilda/infrastructure/issues/2 the database has been documented.
